services:
  mysql:
    image: mysql:latest
    container_name: mysql-hospital
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: hospital_db
      MYSQL_USER: hospital_user
      MYSQL_PASSWORD: hospital_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hospital-network

volumes:
  mysql_data:

networks:
  hospital-network: